// ─────────────────────────────────────────────────────────────────────────────
// Verilog code generator.
// Walks a Circuit and emits human-readable, commented Verilog.
// Only supports the node types defined in the app – not a general-purpose
// HDL compiler.
// ─────────────────────────────────────────────────────────────────────────────

import type {
  Circuit, CircuitNode,
  InputPinProperties, OutputPinProperties, Counter8Properties,
  MmioRegisterProperties, NodeType,
} from '../simulator/types';

// ─────────────────────────────────────────────────────────────────────────────
// Main entry point
// ─────────────────────────────────────────────────────────────────────────────

export function generateVerilog(circuit: Circuit, moduleName = 'circuit'): string {
  const lines: string[] = [];

  const inputs  = circuit.nodes.filter(n => n.type === 'input_pin');
  const outputs = circuit.nodes.filter(n => n.type === 'output_pin');
  const gates   = circuit.nodes.filter(n => isGate(n.type));
  const seqs    = circuit.nodes.filter(n => isSequential(n.type));
  const mmios   = circuit.nodes.filter(n => n.type === 'mmio_register');

  const wireMap = buildWireSourceMap(circuit);

  // ── Module header ──────────────────────────────────────────────────────────
  lines.push(`// Generated by Verilog + Rust Hardware Lab`);
  lines.push(`// This Verilog describes HARDWARE behavior, not a program.`);
  lines.push(`// All assign statements are always active simultaneously.`);
  lines.push(``);
  lines.push(`module ${moduleName} (`);

  const ports: string[] = [];
  for (const n of inputs) {
    const props = n.properties as InputPinProperties;
    const pinName = safeName(props.pinName);
    ports.push(`    input wire ${pinName}`);
  }
  for (const n of outputs) {
    const props = n.properties as OutputPinProperties;
    const pinName = safeName(props.pinName);
    const srcPort = wireMap.get(portId(n.id, 'in'));
    const width = srcPort ? getPortWidth(circuit, srcPort) : 1;
    const widthStr = width > 1 ? `[${width - 1}:0] ` : '';
    ports.push(`    output ${seqs.length > 0 ? 'reg ' : 'wire '}${widthStr}${pinName}`);
  }
  lines.push(ports.join(',\n'));
  lines.push(`);`);
  lines.push(``);

  // ── Internal wire declarations ─────────────────────────────────────────────
  if (gates.length > 0 || seqs.length > 0) {
    lines.push(`    // ── Internal signals ─────────────────────────────────────────`);
    for (const n of gates) {
      for (const op of n.outputPorts) {
        lines.push(`    wire ${safePortName(n, op.name)};`);
      }
    }
    for (const n of seqs) {
      if (n.type === 'counter8') {
        lines.push(`    reg [7:0] ${safeName(n.label)}_count;`);
      } else if (n.type === 'register8') {
        lines.push(`    reg [7:0] ${safeName(n.label)}_q;`);
      } else if (n.type === 'dff') {
        lines.push(`    reg ${safeName(n.label)}_q;`);
      }
    }
    lines.push(``);
  }

  // ── Combinational assigns ──────────────────────────────────────────────────
  if (gates.length > 0) {
    lines.push(`    // ── Combinational logic ──────────────────────────────────────`);
    lines.push(`    // These are always active – not executed line by line like code.`);
    for (const n of gates) {
      const gateLines = generateGateAssign(n, circuit, wireMap);
      lines.push(...gateLines);
    }
    lines.push(``);
  }

  // ── Sequential always blocks ───────────────────────────────────────────────
  if (seqs.length > 0) {
    lines.push(`    // ── Sequential logic (clocked) ───────────────────────────────`);
    lines.push(`    // The always @(posedge clk) block runs on each rising clock edge.`);
    for (const n of seqs) {
      const seqLines = generateSequentialBlock(n, circuit, wireMap, inputs);
      lines.push(...seqLines);
    }
    lines.push(``);
  }

  // ── Output assignments ─────────────────────────────────────────────────────
  if (outputs.length > 0 && seqs.length === 0) {
    lines.push(`    // ── Output assignments ───────────────────────────────────────`);
    for (const n of outputs) {
      const props = n.properties as OutputPinProperties;
      const src = wireMap.get(portId(n.id, 'in'));
      if (src) {
        lines.push(`    assign ${safeName(props.pinName)} = ${resolveSignalName(src, circuit)};`);
      }
    }
    lines.push(``);
  } else if (outputs.length > 0 && seqs.length > 0) {
    // Output driven from register/counter output
    lines.push(`    // ── Output assignments ───────────────────────────────────────`);
    for (const n of outputs) {
      const props = n.properties as OutputPinProperties;
      const src = wireMap.get(portId(n.id, 'in'));
      if (src) {
        const srcNode = findNodeByPortId(circuit, src);
        if (srcNode && isSequential(srcNode.type)) {
          const sigName = sequentialOutputSignalName(srcNode);
          lines.push(`    assign ${safeName(props.pinName)} = ${sigName};`);
        } else {
          lines.push(`    assign ${safeName(props.pinName)} = ${resolveSignalName(src, circuit)};`);
        }
      }
    }
    lines.push(``);
  }

  // ── MMIO register interface (if present) ───────────────────────────────────
  if (mmios.length > 0) {
    lines.push(`    // ── Memory-mapped register interface ────────────────────────`);
    lines.push(`    // These registers are accessed by firmware via volatile reads/writes.`);
    for (const n of mmios) {
      const props = n.properties as MmioRegisterProperties;
      lines.push(`    //`);
      lines.push(`    // Module: ${props.moduleName}  Base: ${props.baseAddress}`);
      for (const reg of props.registers) {
        lines.push(`    //   +${reg.offset.toString().padStart(2)} ${reg.name.padEnd(10)} [${reg.access}] – ${reg.description}`);
      }
    }
    lines.push(``);
  }

  // ── endmodule ──────────────────────────────────────────────────────────────
  lines.push(`endmodule`);

  return lines.join('\n');
}

// ─────────────────────────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────────────────────────

function isGate(type: NodeType): boolean {
  return ['not', 'and', 'or', 'xor', 'comparator', 'mux2to1'].includes(type);
}

function isSequential(type: NodeType): boolean {
  return ['dff', 'register8', 'counter8'].includes(type);
}

function safeName(s: string): string {
  return s.replace(/[^a-zA-Z0-9_]/g, '_').replace(/^(\d)/, '_$1');
}

function safePortName(node: CircuitNode, portName: string): string {
  return `${safeName(node.label)}_${portName}`;
}

function portId(nodeId: string, portName: string): string {
  return `${nodeId}:${portName}`;
}

/** Build a map: toPortId → fromPortId */
function buildWireSourceMap(circuit: Circuit): Map<string, string> {
  const m = new Map<string, string>();
  for (const w of circuit.wires) {
    m.set(w.to.portId, w.from.portId);
  }
  return m;
}

function getPortWidth(circuit: Circuit, fromPortId: string): number {
  const [nodeId, portName] = fromPortId.split(':');
  const node = circuit.nodes.find(n => n.id === nodeId);
  if (!node) return 1;
  const port = [...node.outputPorts, ...node.inputPorts].find(p => p.id === fromPortId || p.name === portName);
  return port?.width ?? 1;
}

function findNodeByPortId(circuit: Circuit, pid: string): CircuitNode | undefined {
  const nodeId = pid.split(':')[0];
  return circuit.nodes.find(n => n.id === nodeId);
}

function resolveSignalName(fromPortId: string, circuit: Circuit): string {
  const node = findNodeByPortId(circuit, fromPortId);
  if (!node) return "'x";
  if (node.type === 'input_pin') {
    return safeName((node.properties as InputPinProperties).pinName);
  }
  const portName = fromPortId.split(':')[1] ?? fromPortId.split(':').pop()!;
  return safePortName(node, portName);
}

function sequentialOutputSignalName(node: CircuitNode): string {
  if (node.type === 'counter8') return `${safeName(node.label)}_count`;
  if (node.type === 'register8') return `${safeName(node.label)}_q`;
  if (node.type === 'dff') return `${safeName(node.label)}_q`;
  return safeName(node.label);
}

function resolveInputSignal(
  portId: string,
  circuit: Circuit,
  wireMap: Map<string, string>,
): string {
  const src = wireMap.get(portId);
  if (!src) return "'x";
  const node = findNodeByPortId(circuit, src);
  if (!node) return "'x";
  if (node.type === 'input_pin') {
    return safeName((node.properties as InputPinProperties).pinName);
  }
  if (isSequential(node.type)) {
    return sequentialOutputSignalName(node);
  }
  const portName = src.split(':')[1] ?? src.split(':').pop()!;
  return safePortName(node, portName);
}

function generateGateAssign(
  node: CircuitNode,
  circuit: Circuit,
  wireMap: Map<string, string>,
): string[] {
  const lines: string[] = [];
  const lbl = safeName(node.label);

  const inp = (pname: string) => resolveInputSignal(portId(node.id, pname), circuit, wireMap);

  switch (node.type) {
    case 'not':
      lines.push(`    assign ${lbl}_y = ~${inp('a')}; // NOT gate`);
      break;
    case 'and':
      lines.push(`    assign ${lbl}_y = ${inp('a')} & ${inp('b')}; // AND gate`);
      break;
    case 'or':
      lines.push(`    assign ${lbl}_y = ${inp('a')} | ${inp('b')}; // OR gate`);
      break;
    case 'xor':
      lines.push(`    assign ${lbl}_y = ${inp('a')} ^ ${inp('b')}; // XOR gate`);
      break;
    case 'comparator': {
      const a = inp('a'); const b = inp('b');
      lines.push(`    assign ${lbl}_eq = (${a} == ${b}); // Comparator EQ`);
      lines.push(`    assign ${lbl}_lt = (${a} <  ${b}); // Comparator LT`);
      lines.push(`    assign ${lbl}_gt = (${a} >  ${b}); // Comparator GT`);
      break;
    }
    case 'mux2to1':
      lines.push(`    assign ${lbl}_y = ${inp('sel')} ? ${inp('b')} : ${inp('a')}; // 2-to-1 Mux`);
      break;
  }
  return lines;
}

function generateSequentialBlock(
  node: CircuitNode,
  circuit: Circuit,
  wireMap: Map<string, string>,
  inputs: CircuitNode[],
): string[] {
  const lines: string[] = [];
  const lbl = safeName(node.label);

  const clkInput = inputs.find(n => (n.properties as InputPinProperties).pinName.includes('clk'));
  const clkName = clkInput ? safeName((clkInput.properties as InputPinProperties).pinName) : 'clk';

  const inp = (pname: string) => resolveInputSignal(portId(node.id, pname), circuit, wireMap);

  switch (node.type) {
    case 'dff': {
      const rst = inp('rst');
      const d   = inp('d');
      lines.push(`    // D Flip-Flop: captures D on rising clock edge`);
      lines.push(`    always @(posedge ${clkName}) begin`);
      lines.push(`        if (${rst}) begin`);
      lines.push(`            ${lbl}_q <= 1'b0;`);
      lines.push(`        end else begin`);
      lines.push(`            ${lbl}_q <= ${d};`);
      lines.push(`        end`);
      lines.push(`    end`);
      break;
    }
    case 'register8': {
      const rst = inp('rst');
      const en  = inp('en');
      const d   = inp('d');
      lines.push(`    // 8-bit Register: loads when enable is high`);
      lines.push(`    always @(posedge ${clkName}) begin`);
      lines.push(`        if (${rst}) begin`);
      lines.push(`            ${lbl}_q <= 8'd0;`);
      lines.push(`        end else if (${en}) begin`);
      lines.push(`            ${lbl}_q <= ${d};`);
      lines.push(`        end`);
      lines.push(`    end`);
      break;
    }
    case 'counter8': {
      const rst = inp('rst');
      const en  = inp('en');
      const max = (node.properties as Counter8Properties).maxCount ?? 255;
      lines.push(`    // 8-bit Counter: increments on each clock edge when enabled`);
      lines.push(`    always @(posedge ${clkName}) begin`);
      lines.push(`        if (${rst}) begin`);
      lines.push(`            ${lbl}_count <= 8'd0;`);
      lines.push(`        end else if (${en}) begin`);
      if (max < 255) {
        lines.push(`            if (${lbl}_count == 8'd${max})`);
        lines.push(`                ${lbl}_count <= 8'd0;`);
        lines.push(`            else`);
        lines.push(`                ${lbl}_count <= ${lbl}_count + 8'd1;`);
      } else {
        lines.push(`            ${lbl}_count <= ${lbl}_count + 8'd1;`);
      }
      lines.push(`        end`);
      lines.push(`    end`);
      break;
    }
  }

  return lines;
}
