// ─────────────────────────────────────────────────────────────────────────────
// Verilog code generator.
// Walks a Circuit and emits human-readable, commented Verilog.
// Only supports the node types defined in the app – not a general-purpose
// HDL compiler.
// ─────────────────────────────────────────────────────────────────────────────

import type {
  Circuit, CircuitNode,
  InputPinProperties, OutputPinProperties, CounterProperties,
  MmioRegisterProperties, TimerPwmProperties, SpiControllerProperties,
  PidControllerProperties, AdcProperties, NodeType,
} from '../simulator/types';
import { getNodeWidth } from '../simulator/types';

// ─────────────────────────────────────────────────────────────────────────────
// Main entry point
// ─────────────────────────────────────────────────────────────────────────────

export function generateVerilog(circuit: Circuit, moduleName = 'circuit'): string {
  const lines: string[] = [];

  const inputs  = circuit.nodes.filter(n => n.type === 'input_pin');
  const outputs = circuit.nodes.filter(n => n.type === 'output_pin');
  const gates   = circuit.nodes.filter(n => isGate(n.type));
  const seqs    = circuit.nodes.filter(n => isSequential(n.type));
  const mmios   = circuit.nodes.filter(n => n.type === 'mmio_register');
  const timers  = circuit.nodes.filter(n => n.type === 'timer_pwm_capture');
  const spis    = circuit.nodes.filter(n => n.type === 'spi_controller');
  const pids    = circuit.nodes.filter(n => n.type === 'pid_controller');
  const adcs    = circuit.nodes.filter(n => n.type === 'adc');

  const wireMap = buildWireSourceMap(circuit);

  // ── Module header ──────────────────────────────────────────────────────────
  lines.push(`// Generated by Verilog + Rust Hardware Lab`);
  lines.push(`// This Verilog describes HARDWARE behavior, not a program.`);
  lines.push(`// All assign statements are always active simultaneously.`);
  lines.push(``);
  lines.push(`module ${moduleName} (`);

  const ports: string[] = [];
  for (const n of inputs) {
    const props = n.properties as InputPinProperties;
    const pinName = safeName(props.pinName);
    ports.push(`    input wire ${pinName}`);
  }
  for (const n of outputs) {
    const props = n.properties as OutputPinProperties;
    const pinName = safeName(props.pinName);
    const srcPort = wireMap.get(portId(n.id, 'in'));
    const width = srcPort ? getPortWidth(circuit, srcPort) : 1;
    const widthStr = width > 1 ? `[${width - 1}:0] ` : '';
    ports.push(`    output ${seqs.length > 0 ? 'reg ' : 'wire '}${widthStr}${pinName}`);
  }
  lines.push(ports.join(',\n'));
  lines.push(`);`);
  lines.push(``);

  // ── Internal wire declarations ─────────────────────────────────────────────
  if (gates.length > 0 || seqs.length > 0) {
    lines.push(`    // ── Internal signals ─────────────────────────────────────────`);
    for (const n of gates) {
      for (const op of n.outputPorts) {
        lines.push(`    wire ${safePortName(n, op.name)};`);
      }
    }
    for (const n of seqs) {
      if (n.type === 'counter' || n.type === 'counter8') {
        const w = getNodeWidth(n.properties);
        lines.push(`    reg [${w - 1}:0] ${safeName(n.label)}_count;`);
      } else if (n.type === 'register' || n.type === 'register8') {
        const w = getNodeWidth(n.properties);
        lines.push(`    reg [${w - 1}:0] ${safeName(n.label)}_q;`);
      } else if (n.type === 'dff') {
        lines.push(`    reg ${safeName(n.label)}_q;`);
      }
    }
    lines.push(``);
  }

  // ── Combinational assigns ──────────────────────────────────────────────────
  if (gates.length > 0) {
    lines.push(`    // ── Combinational logic ──────────────────────────────────────`);
    lines.push(`    // These are always active – not executed line by line like code.`);
    for (const n of gates) {
      const gateLines = generateGateAssign(n, circuit, wireMap);
      lines.push(...gateLines);
    }
    lines.push(``);
  }

  // ── Sequential always blocks ───────────────────────────────────────────────
  if (seqs.length > 0) {
    lines.push(`    // ── Sequential logic (clocked) ───────────────────────────────`);
    lines.push(`    // The always @(posedge clk) block runs on each rising clock edge.`);
    for (const n of seqs) {
      const seqLines = generateSequentialBlock(n, circuit, wireMap, inputs);
      lines.push(...seqLines);
    }
    lines.push(``);
  }

  // ── Output assignments ─────────────────────────────────────────────────────
  if (outputs.length > 0 && seqs.length === 0) {
    lines.push(`    // ── Output assignments ───────────────────────────────────────`);
    for (const n of outputs) {
      const props = n.properties as OutputPinProperties;
      const src = wireMap.get(portId(n.id, 'in'));
      if (src) {
        lines.push(`    assign ${safeName(props.pinName)} = ${resolveSignalName(src, circuit)};`);
      }
    }
    lines.push(``);
  } else if (outputs.length > 0 && seqs.length > 0) {
    // Output driven from register/counter output
    lines.push(`    // ── Output assignments ───────────────────────────────────────`);
    for (const n of outputs) {
      const props = n.properties as OutputPinProperties;
      const src = wireMap.get(portId(n.id, 'in'));
      if (src) {
        const srcNode = findNodeByPortId(circuit, src);
        if (srcNode && isSequential(srcNode.type)) {
          const sigName = sequentialOutputSignalName(srcNode);
          lines.push(`    assign ${safeName(props.pinName)} = ${sigName};`);
        } else {
          lines.push(`    assign ${safeName(props.pinName)} = ${resolveSignalName(src, circuit)};`);
        }
      }
    }
    lines.push(``);
  }

  // ── MMIO register interface (if present) ───────────────────────────────────
  if (mmios.length > 0) {
    lines.push(`    // ── Memory-mapped register interface ────────────────────────`);
    lines.push(`    // These registers are accessed by firmware via volatile reads/writes.`);
    for (const n of mmios) {
      const props = n.properties as MmioRegisterProperties;
      lines.push(`    //`);
      lines.push(`    // Module: ${props.moduleName}  Base: ${props.baseAddress}`);
      for (const reg of props.registers) {
        lines.push(`    //   +${reg.offset.toString().padStart(2)} ${reg.name.padEnd(10)} [${reg.access}] – ${reg.description}`);
      }
    }
    lines.push(``);
  }

  // ── Timer/PWM/Capture (if present) ──────────────────────────────────────────
  if (timers.length > 0) {
    for (const n of timers) {
      const props = n.properties as TimerPwmProperties;
      const lbl = safeName(props.moduleName);
      const clkInput = inputs.find(nd => (nd.properties as InputPinProperties).pinName.includes('clk'));
      const clkName = clkInput ? safeName((clkInput.properties as InputPinProperties).pinName) : 'clk';
      const rstInput = inputs.find(nd => (nd.properties as InputPinProperties).pinName.includes('rst'));
      const rstName = rstInput ? safeName((rstInput.properties as InputPinProperties).pinName) : 'rst';

      lines.push(`    // ── Timer/PWM with Input Capture ──────────────────────────────`);
      lines.push(`    // Module: ${props.moduleName}  Base: ${props.baseAddress}`);
      lines.push(`    // Prescaler divides clock, counter counts to PERIOD, then overflows.`);
      lines.push(`    // PWM outputs go HIGH while counter < compare threshold.`);
      lines.push(`    //`);
      for (const reg of props.registers) {
        lines.push(`    //   +0x${reg.offset.toString(16).padStart(2, '0')} ${reg.name.padEnd(10)} [${reg.access}] – ${reg.description}`);
      }
      lines.push(``);
      lines.push(`    // Configuration registers (firmware-writable)`);
      lines.push(`    reg [15:0] ${lbl}_ctrl;`);
      lines.push(`    reg [15:0] ${lbl}_prescale;`);
      lines.push(`    reg [15:0] ${lbl}_period;`);
      lines.push(`    reg [15:0] ${lbl}_cmp0;`);
      lines.push(`    reg [15:0] ${lbl}_cmp1;`);
      lines.push(``);
      lines.push(`    // Hardware state registers`);
      lines.push(`    reg [15:0] ${lbl}_prescaler_cnt;`);
      lines.push(`    reg [15:0] ${lbl}_counter;`);
      lines.push(`    reg [15:0] ${lbl}_capture;`);
      lines.push(`    reg [15:0] ${lbl}_status;`);
      lines.push(`    reg        ${lbl}_cap_prev;`);
      lines.push(``);
      lines.push(`    // Prescaler tick: counter advances when prescaler overflows`);
      lines.push(`    wire ${lbl}_tick = (${lbl}_prescaler_cnt >= ${lbl}_prescale);`);
      lines.push(``);
      lines.push(`    // PWM output: HIGH while counter < compare value`);
      lines.push(`    assign pwm0 = (${lbl}_counter < ${lbl}_cmp0);`);
      lines.push(`    assign pwm1 = (${lbl}_counter < ${lbl}_cmp1);`);
      lines.push(``);
      lines.push(`    // IRQ: any enabled status flag is set`);
      lines.push(`    assign irq = |(${lbl}_status & ${lbl}_ctrl[7:4]);`);
      lines.push(``);
      lines.push(`    always @(posedge ${clkName}) begin`);
      lines.push(`        if (${rstName}) begin`);
      lines.push(`            ${lbl}_prescaler_cnt <= 16'd0;`);
      lines.push(`            ${lbl}_counter      <= 16'd0;`);
      lines.push(`            ${lbl}_capture      <= 16'd0;`);
      lines.push(`            ${lbl}_status       <= 16'd0;`);
      lines.push(`            ${lbl}_cap_prev     <= 1'b0;`);
      lines.push(`        end else if (${lbl}_ctrl[0]) begin  // enabled`);
      lines.push(`            // Prescaler`);
      lines.push(`            if (${lbl}_tick) begin`);
      lines.push(`                ${lbl}_prescaler_cnt <= 16'd0;`);
      lines.push(`                // Main counter`);
      lines.push(`                if (${lbl}_counter >= ${lbl}_period)`);
      lines.push(`                    ${lbl}_counter <= 16'd0;  // overflow`);
      lines.push(`                else`);
      lines.push(`                    ${lbl}_counter <= ${lbl}_counter + 16'd1;`);
      lines.push(`            end else begin`);
      lines.push(`                ${lbl}_prescaler_cnt <= ${lbl}_prescaler_cnt + 16'd1;`);
      lines.push(`            end`);
      lines.push(``);
      lines.push(`            // Input capture: edge detection`);
      lines.push(`            ${lbl}_cap_prev <= capture_in;`);
      lines.push(`            if (!${lbl}_cap_prev && capture_in)  // rising edge`);
      lines.push(`                ${lbl}_capture <= ${lbl}_counter;`);
      lines.push(`        end`);
      lines.push(`    end`);
      lines.push(``);
    }
  }

  // ── SPI Controller (if present) ──────────────────────────────────────────────
  if (spis.length > 0) {
    for (const n of spis) {
      const props = n.properties as SpiControllerProperties;
      const lbl = safeName(props.moduleName);
      const clkInput = inputs.find(nd => (nd.properties as InputPinProperties).pinName.includes('clk'));
      const clkName = clkInput ? safeName((clkInput.properties as InputPinProperties).pinName) : 'clk';
      const rstInput = inputs.find(nd => (nd.properties as InputPinProperties).pinName.includes('rst'));
      const rstName = rstInput ? safeName((rstInput.properties as InputPinProperties).pinName) : 'rst';

      lines.push(`    // ── SPI Controller (Master) ──────────────────────────────────────`);
      lines.push(`    // Module: ${props.moduleName}  Base: ${props.baseAddress}`);
      lines.push(`    // Full-duplex serial interface: MOSI out, MISO in, synchronized to SCLK.`);
      lines.push(`    //`);
      for (const reg of props.registers) {
        lines.push(`    //   +0x${reg.offset.toString(16).padStart(2, '0')} ${reg.name.padEnd(10)} [${reg.access}] – ${reg.description}`);
      }
      lines.push(``);
      lines.push(`    // Configuration registers`);
      lines.push(`    reg [15:0] ${lbl}_ctrl;`);
      lines.push(`    reg [15:0] ${lbl}_clk_div;`);
      lines.push(``);
      lines.push(`    // Shift registers and state`);
      lines.push(`    reg [7:0]  ${lbl}_tx_shift;`);
      lines.push(`    reg [7:0]  ${lbl}_rx_shift;`);
      lines.push(`    reg [7:0]  ${lbl}_rx_data;`);
      lines.push(`    reg [3:0]  ${lbl}_bit_cnt;`);
      lines.push(`    reg [15:0] ${lbl}_div_cnt;`);
      lines.push(`    reg        ${lbl}_sclk_phase;`);
      lines.push(`    reg        ${lbl}_busy;`);
      lines.push(`    reg        ${lbl}_cs;`);
      lines.push(`    reg [15:0] ${lbl}_status;`);
      lines.push(``);
      lines.push(`    // Output assignments`);
      lines.push(`    assign sclk  = ${lbl}_busy ? ${lbl}_sclk_phase : 1'b0;`);
      lines.push(`    assign mosi  = ${lbl}_tx_shift[7];  // MSB first`);
      lines.push(`    assign cs_n  = ~${lbl}_cs;           // active low`);
      lines.push(`    assign irq   = (${lbl}_ctrl[4]) & (${lbl}_status[1]); // IRQ on RX_READY`);
      lines.push(``);
      lines.push(`    always @(posedge ${clkName}) begin`);
      lines.push(`        if (${rstName}) begin`);
      lines.push(`            ${lbl}_tx_shift   <= 8'd0;`);
      lines.push(`            ${lbl}_rx_shift   <= 8'd0;`);
      lines.push(`            ${lbl}_rx_data    <= 8'd0;`);
      lines.push(`            ${lbl}_bit_cnt    <= 4'd0;`);
      lines.push(`            ${lbl}_div_cnt    <= 16'd0;`);
      lines.push(`            ${lbl}_sclk_phase <= 1'b0;`);
      lines.push(`            ${lbl}_busy       <= 1'b0;`);
      lines.push(`            ${lbl}_cs         <= 1'b0;`);
      lines.push(`            ${lbl}_status     <= 16'd0;`);
      lines.push(`        end else if (${lbl}_busy) begin`);
      lines.push(`            ${lbl}_div_cnt <= ${lbl}_div_cnt + 16'd1;`);
      lines.push(`            if (${lbl}_div_cnt >= ${lbl}_clk_div) begin`);
      lines.push(`                ${lbl}_div_cnt <= 16'd0;`);
      lines.push(`                if (!${lbl}_sclk_phase) begin`);
      lines.push(`                    // Rising SCLK: sample MISO`);
      lines.push(`                    ${lbl}_rx_shift <= {${lbl}_rx_shift[6:0], miso};`);
      lines.push(`                    ${lbl}_sclk_phase <= 1'b1;`);
      lines.push(`                end else begin`);
      lines.push(`                    // Falling SCLK: shift MOSI`);
      lines.push(`                    ${lbl}_tx_shift <= {${lbl}_tx_shift[6:0], 1'b0};`);
      lines.push(`                    ${lbl}_sclk_phase <= 1'b0;`);
      lines.push(`                    ${lbl}_bit_cnt <= ${lbl}_bit_cnt + 4'd1;`);
      lines.push(`                    if (${lbl}_bit_cnt == 4'd7) begin`);
      lines.push(`                        ${lbl}_busy    <= 1'b0;`);
      lines.push(`                        ${lbl}_cs      <= 1'b0;`);
      lines.push(`                        ${lbl}_rx_data <= ${lbl}_rx_shift;`);
      lines.push(`                        ${lbl}_status[0] <= 1'b0;  // clear BUSY`);
      lines.push(`                        ${lbl}_status[1] <= 1'b1;  // set RX_READY`);
      lines.push(`                    end`);
      lines.push(`                end`);
      lines.push(`            end`);
      lines.push(`        end`);
      lines.push(`    end`);
      lines.push(``);
    }
  }

  // ── PID Controller (if present) ────────────────────────────────────────────
  if (pids.length > 0) {
    for (const n of pids) {
      const props = n.properties as PidControllerProperties;
      const lbl = safeName(props.moduleName);
      const clkInput = inputs.find(nd => (nd.properties as InputPinProperties).pinName.includes('clk'));
      const clkName = clkInput ? safeName((clkInput.properties as InputPinProperties).pinName) : 'clk';
      const rstInput = inputs.find(nd => (nd.properties as InputPinProperties).pinName.includes('rst'));
      const rstName = rstInput ? safeName((rstInput.properties as InputPinProperties).pinName) : 'rst';

      lines.push(`    // ── PID Controller ────────────────────────────────────────────────`);
      lines.push(`    // Module: ${props.moduleName}  Base: ${props.baseAddress}`);
      lines.push(`    // Fixed-point (Q8.8) multiply-accumulate for drone stabilization.`);
      lines.push(`    //`);
      for (const reg of props.registers) {
        lines.push(`    //   +0x${reg.offset.toString(16).padStart(2, '0')} ${reg.name.padEnd(10)} [${reg.access}] – ${reg.description}`);
      }
      lines.push(``);
      lines.push(`    // Gain registers (Q8.8 fixed-point: upper 8 = integer, lower 8 = fraction)`);
      lines.push(`    reg [15:0] ${lbl}_kp;`);
      lines.push(`    reg [15:0] ${lbl}_ki;`);
      lines.push(`    reg [15:0] ${lbl}_kd;`);
      lines.push(`    reg [15:0] ${lbl}_setpoint;`);
      lines.push(``);
      lines.push(`    // Internal state`);
      lines.push(`    reg signed [15:0] ${lbl}_error;`);
      lines.push(`    reg signed [15:0] ${lbl}_prev_error;`);
      lines.push(`    reg signed [15:0] ${lbl}_integral;`);
      lines.push(`    reg [7:0]         ${lbl}_output;`);
      lines.push(`    reg               ${lbl}_done;`);
      lines.push(``);
      lines.push(`    // Intermediate wires`);
      lines.push(`    wire signed [31:0] ${lbl}_p_term = ($signed(${lbl}_kp) * ${lbl}_error) >>> 8;`);
      lines.push(`    wire signed [31:0] ${lbl}_i_term = ($signed(${lbl}_ki) * ${lbl}_integral) >>> 8;`);
      lines.push(`    wire signed [31:0] ${lbl}_d_term = ($signed(${lbl}_kd) * (${lbl}_error - ${lbl}_prev_error)) >>> 8;`);
      lines.push(`    wire signed [31:0] ${lbl}_sum    = ${lbl}_p_term + ${lbl}_i_term + ${lbl}_d_term;`);
      lines.push(``);
      lines.push(`    assign irq = ${lbl}_done;`);
      lines.push(``);
      lines.push(`    always @(posedge ${clkName}) begin`);
      lines.push(`        if (${rstName}) begin`);
      lines.push(`            ${lbl}_error      <= 16'sd0;`);
      lines.push(`            ${lbl}_prev_error <= 16'sd0;`);
      lines.push(`            ${lbl}_integral   <= 16'sd0;`);
      lines.push(`            ${lbl}_output     <= 8'd0;`);
      lines.push(`            ${lbl}_done       <= 1'b0;`);
      lines.push(`        end else if (update) begin`);
      lines.push(`            ${lbl}_error <= $signed({8'd0, setpoint}) - $signed({8'd0, measured});`);
      lines.push(`            ${lbl}_prev_error <= ${lbl}_error;`);
      lines.push(``);
      lines.push(`            // Anti-windup: clamp integral to ±2048`);
      lines.push(`            if (${lbl}_integral + ${lbl}_error > 16'sd2048)`);
      lines.push(`                ${lbl}_integral <= 16'sd2048;`);
      lines.push(`            else if (${lbl}_integral + ${lbl}_error < -16'sd2048)`);
      lines.push(`                ${lbl}_integral <= -16'sd2048;`);
      lines.push(`            else`);
      lines.push(`                ${lbl}_integral <= ${lbl}_integral + ${lbl}_error;`);
      lines.push(``);
      lines.push(`            // Clamp output to 0–255`);
      lines.push(`            if (${lbl}_sum > 32'sd255)`);
      lines.push(`                ${lbl}_output <= 8'd255;`);
      lines.push(`            else if (${lbl}_sum < 32'sd0)`);
      lines.push(`                ${lbl}_output <= 8'd0;`);
      lines.push(`            else`);
      lines.push(`                ${lbl}_output <= ${lbl}_sum[7:0];`);
      lines.push(`            ${lbl}_done <= 1'b1;`);
      lines.push(`        end else begin`);
      lines.push(`            ${lbl}_done <= 1'b0;`);
      lines.push(`        end`);
      lines.push(`    end`);
      lines.push(``);
    }
  }

  // ── ADC (if present) ──────────────────────────────────────────────────────
  if (adcs.length > 0) {
    for (const n of adcs) {
      const props = n.properties as AdcProperties;
      const lbl = safeName(props.moduleName);
      const clkInput = inputs.find(nd => (nd.properties as InputPinProperties).pinName.includes('clk'));
      const clkName = clkInput ? safeName((clkInput.properties as InputPinProperties).pinName) : 'clk';
      const rstInput = inputs.find(nd => (nd.properties as InputPinProperties).pinName.includes('rst'));
      const rstName = rstInput ? safeName((rstInput.properties as InputPinProperties).pinName) : 'rst';

      lines.push(`    // ── ADC (Analog-to-Digital Converter) ─────────────────────────────`);
      lines.push(`    // Module: ${props.moduleName}  Base: ${props.baseAddress}`);
      lines.push(`    // State machine: IDLE → SAMPLING → CONVERTING → DONE`);
      lines.push(`    //`);
      for (const reg of props.registers) {
        lines.push(`    //   +0x${reg.offset.toString(16).padStart(2, '0')} ${reg.name.padEnd(14)} [${reg.access}] – ${reg.description}`);
      }
      lines.push(``);
      lines.push(`    // ADC state machine`);
      lines.push(`    localparam ${lbl}_IDLE      = 2'd0;`);
      lines.push(`    localparam ${lbl}_SAMPLING  = 2'd1;`);
      lines.push(`    localparam ${lbl}_CONVERTING = 2'd2;`);
      lines.push(`    localparam ${lbl}_DONE      = 2'd3;`);
      lines.push(``);
      lines.push(`    reg [1:0]  ${lbl}_state;`);
      lines.push(`    reg [7:0]  ${lbl}_sample;`);
      lines.push(`    reg [7:0]  ${lbl}_result;`);
      lines.push(`    reg [15:0] ${lbl}_sample_cnt;`);
      lines.push(`    reg [3:0]  ${lbl}_bit;`);
      lines.push(`    reg [15:0] ${lbl}_status;`);
      lines.push(`    reg [15:0] ${lbl}_ctrl;`);
      lines.push(`    reg [15:0] ${lbl}_sample_time;`);
      lines.push(`    reg [15:0] ${lbl}_thresh_hi;`);
      lines.push(`    reg [15:0] ${lbl}_thresh_lo;`);
      lines.push(``);
      lines.push(`    assign eoc = ${lbl}_status[1];`);
      lines.push(`    assign irq = (${lbl}_ctrl[4] & ${lbl}_status[1]) | (${lbl}_ctrl[5] & ${lbl}_status[3]);`);
      lines.push(``);
      lines.push(`    always @(posedge ${clkName}) begin`);
      lines.push(`        if (${rstName}) begin`);
      lines.push(`            ${lbl}_state      <= ${lbl}_IDLE;`);
      lines.push(`            ${lbl}_sample     <= 8'd0;`);
      lines.push(`            ${lbl}_result     <= 8'd0;`);
      lines.push(`            ${lbl}_sample_cnt <= 16'd0;`);
      lines.push(`            ${lbl}_bit        <= 4'd7;`);
      lines.push(`            ${lbl}_status     <= 16'd0;`);
      lines.push(`        end else begin`);
      lines.push(`            case (${lbl}_state)`);
      lines.push(`                ${lbl}_IDLE: begin`);
      lines.push(`                    if (trigger || ${lbl}_ctrl[1]) begin`);
      lines.push(`                        ${lbl}_state      <= ${lbl}_SAMPLING;`);
      lines.push(`                        ${lbl}_sample_cnt <= 16'd0;`);
      lines.push(`                        ${lbl}_status[0]  <= 1'b1;  // BUSY`);
      lines.push(`                        ${lbl}_status[1]  <= 1'b0;  // clear EOC`);
      lines.push(`                    end`);
      lines.push(`                end`);
      lines.push(`                ${lbl}_SAMPLING: begin`);
      lines.push(`                    ${lbl}_sample     <= analog_in;  // latch input`);
      lines.push(`                    ${lbl}_sample_cnt <= ${lbl}_sample_cnt + 16'd1;`);
      lines.push(`                    if (${lbl}_sample_cnt >= ${lbl}_sample_time) begin`);
      lines.push(`                        ${lbl}_state  <= ${lbl}_CONVERTING;`);
      lines.push(`                        ${lbl}_bit    <= 4'd7;`);
      lines.push(`                        ${lbl}_result <= 8'd0;`);
      lines.push(`                    end`);
      lines.push(`                end`);
      lines.push(`                ${lbl}_CONVERTING: begin`);
      lines.push(`                    ${lbl}_result[${lbl}_bit] <= ${lbl}_sample[${lbl}_bit];`);
      lines.push(`                    if (${lbl}_bit == 4'd0)`);
      lines.push(`                        ${lbl}_state <= ${lbl}_DONE;`);
      lines.push(`                    else`);
      lines.push(`                        ${lbl}_bit <= ${lbl}_bit - 4'd1;`);
      lines.push(`                end`);
      lines.push(`                ${lbl}_DONE: begin`);
      lines.push(`                    ${lbl}_status[0] <= 1'b0;  // clear BUSY`);
      lines.push(`                    ${lbl}_status[1] <= 1'b1;  // set EOC`);
      lines.push(`                    // Watchdog check`);
      lines.push(`                    if (${lbl}_ctrl[3]) begin`);
      lines.push(`                        if (${lbl}_result > ${lbl}_thresh_hi || ${lbl}_result < ${lbl}_thresh_lo)`);
      lines.push(`                            ${lbl}_status[3] <= 1'b1;  // WATCHDOG`);
      lines.push(`                    end`);
      lines.push(`                    ${lbl}_state <= ${lbl}_ctrl[2] ? ${lbl}_SAMPLING : ${lbl}_IDLE;`);
      lines.push(`                end`);
      lines.push(`            endcase`);
      lines.push(`        end`);
      lines.push(`    end`);
      lines.push(``);
    }
  }

  // ── endmodule ──────────────────────────────────────────────────────────────
  lines.push(`endmodule`);

  return lines.join('\n');
}

// ─────────────────────────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────────────────────────

function isGate(type: NodeType): boolean {
  return ['not', 'and', 'or', 'xor', 'comparator', 'mux2to1'].includes(type);
}

function isSequential(type: NodeType): boolean {
  return ['dff', 'register', 'register8', 'counter', 'counter8'].includes(type);
}

function safeName(s: string): string {
  return s.replace(/[^a-zA-Z0-9_]/g, '_').replace(/^(\d)/, '_$1');
}

function safePortName(node: CircuitNode, portName: string): string {
  return `${safeName(node.label)}_${portName}`;
}

function portId(nodeId: string, portName: string): string {
  return `${nodeId}:${portName}`;
}

/** Build a map: toPortId → fromPortId */
function buildWireSourceMap(circuit: Circuit): Map<string, string> {
  const m = new Map<string, string>();
  for (const w of circuit.wires) {
    m.set(w.to.portId, w.from.portId);
  }
  return m;
}

function getPortWidth(circuit: Circuit, fromPortId: string): number {
  const [nodeId, portName] = fromPortId.split(':');
  const node = circuit.nodes.find(n => n.id === nodeId);
  if (!node) return 1;
  const port = [...node.outputPorts, ...node.inputPorts].find(p => p.id === fromPortId || p.name === portName);
  return port?.width ?? 1;
}

function findNodeByPortId(circuit: Circuit, pid: string): CircuitNode | undefined {
  const nodeId = pid.split(':')[0];
  return circuit.nodes.find(n => n.id === nodeId);
}

function resolveSignalName(fromPortId: string, circuit: Circuit): string {
  const node = findNodeByPortId(circuit, fromPortId);
  if (!node) return "'x";
  if (node.type === 'input_pin') {
    return safeName((node.properties as InputPinProperties).pinName);
  }
  const portName = fromPortId.split(':')[1] ?? fromPortId.split(':').pop()!;
  return safePortName(node, portName);
}

function sequentialOutputSignalName(node: CircuitNode): string {
  if (node.type === 'counter' || node.type === 'counter8') return `${safeName(node.label)}_count`;
  if (node.type === 'register' || node.type === 'register8') return `${safeName(node.label)}_q`;
  if (node.type === 'dff') return `${safeName(node.label)}_q`;
  return safeName(node.label);
}

function resolveInputSignal(
  portId: string,
  circuit: Circuit,
  wireMap: Map<string, string>,
): string {
  const src = wireMap.get(portId);
  if (!src) return "'x";
  const node = findNodeByPortId(circuit, src);
  if (!node) return "'x";
  if (node.type === 'input_pin') {
    return safeName((node.properties as InputPinProperties).pinName);
  }
  if (isSequential(node.type)) {
    return sequentialOutputSignalName(node);
  }
  const portName = src.split(':')[1] ?? src.split(':').pop()!;
  return safePortName(node, portName);
}

function generateGateAssign(
  node: CircuitNode,
  circuit: Circuit,
  wireMap: Map<string, string>,
): string[] {
  const lines: string[] = [];
  const lbl = safeName(node.label);

  const inp = (pname: string) => resolveInputSignal(portId(node.id, pname), circuit, wireMap);

  switch (node.type) {
    case 'not':
      lines.push(`    assign ${lbl}_y = ~${inp('a')}; // NOT gate`);
      break;
    case 'and':
      lines.push(`    assign ${lbl}_y = ${inp('a')} & ${inp('b')}; // AND gate`);
      break;
    case 'or':
      lines.push(`    assign ${lbl}_y = ${inp('a')} | ${inp('b')}; // OR gate`);
      break;
    case 'xor':
      lines.push(`    assign ${lbl}_y = ${inp('a')} ^ ${inp('b')}; // XOR gate`);
      break;
    case 'comparator': {
      const a = inp('a'); const b = inp('b');
      lines.push(`    assign ${lbl}_eq = (${a} == ${b}); // Comparator EQ`);
      lines.push(`    assign ${lbl}_lt = (${a} <  ${b}); // Comparator LT`);
      lines.push(`    assign ${lbl}_gt = (${a} >  ${b}); // Comparator GT`);
      break;
    }
    case 'mux2to1':
      lines.push(`    assign ${lbl}_y = ${inp('sel')} ? ${inp('b')} : ${inp('a')}; // 2-to-1 Mux`);
      break;
  }
  return lines;
}

function generateSequentialBlock(
  node: CircuitNode,
  circuit: Circuit,
  wireMap: Map<string, string>,
  inputs: CircuitNode[],
): string[] {
  const lines: string[] = [];
  const lbl = safeName(node.label);

  const clkInput = inputs.find(n => (n.properties as InputPinProperties).pinName.includes('clk'));
  const clkName = clkInput ? safeName((clkInput.properties as InputPinProperties).pinName) : 'clk';

  const inp = (pname: string) => resolveInputSignal(portId(node.id, pname), circuit, wireMap);

  switch (node.type) {
    case 'dff': {
      const rst = inp('rst');
      const d   = inp('d');
      lines.push(`    // D Flip-Flop: captures D on rising clock edge`);
      lines.push(`    always @(posedge ${clkName}) begin`);
      lines.push(`        if (${rst}) begin`);
      lines.push(`            ${lbl}_q <= 1'b0;`);
      lines.push(`        end else begin`);
      lines.push(`            ${lbl}_q <= ${d};`);
      lines.push(`        end`);
      lines.push(`    end`);
      break;
    }
    case 'register':
    case 'register8': {
      const w   = getNodeWidth(node.properties);
      const rst = inp('rst');
      const en  = inp('en');
      const d   = inp('d');
      lines.push(`    // ${w}-bit Register: loads when enable is high`);
      lines.push(`    always @(posedge ${clkName}) begin`);
      lines.push(`        if (${rst}) begin`);
      lines.push(`            ${lbl}_q <= ${w}'d0;`);
      lines.push(`        end else if (${en}) begin`);
      lines.push(`            ${lbl}_q <= ${d};`);
      lines.push(`        end`);
      lines.push(`    end`);
      break;
    }
    case 'counter':
    case 'counter8': {
      const w   = getNodeWidth(node.properties);
      const rst = inp('rst');
      const en  = inp('en');
      const props = node.properties as CounterProperties;
      const maxVal = props.maxCount ?? ((1 << w) - 1) >>> 0;
      const fullRange = maxVal >= ((1 << w) - 1) >>> 0;
      lines.push(`    // ${w}-bit Counter: increments on each clock edge when enabled`);
      lines.push(`    always @(posedge ${clkName}) begin`);
      lines.push(`        if (${rst}) begin`);
      lines.push(`            ${lbl}_count <= ${w}'d0;`);
      lines.push(`        end else if (${en}) begin`);
      if (!fullRange) {
        lines.push(`            if (${lbl}_count == ${w}'d${maxVal})`);
        lines.push(`                ${lbl}_count <= ${w}'d0;`);
        lines.push(`            else`);
        lines.push(`                ${lbl}_count <= ${lbl}_count + ${w}'d1;`);
      } else {
        lines.push(`            ${lbl}_count <= ${lbl}_count + ${w}'d1;`);
      }
      lines.push(`        end`);
      lines.push(`    end`);
      break;
    }
  }

  return lines;
}
