// ─────────────────────────────────────────────────────────────────────────────
// Advanced mode glossary.
// ─────────────────────────────────────────────────────────────────────────────

export interface GlossaryEntry {
  term: string;
  category: 'hardware' | 'firmware' | 'concepts';
  summary: string;
  detail: string;
}

export const GLOSSARY: GlossaryEntry[] = [
  {
    term: 'FPGA vs ASIC',
    category: 'hardware',
    summary: 'FPGA: reprogrammable fabric. ASIC: custom silicon, one-time.',
    detail:
      'An FPGA (Field-Programmable Gate Array) contains thousands of configurable logic blocks that can be wired together by loading a bitstream. You can reprogram it as many times as you want. An ASIC (Application-Specific Integrated Circuit) is fabricated for one specific purpose – the circuit is permanent in silicon. ASICs are faster and cheaper in volume but require millions of dollars and months to produce. FPGAs are ideal for prototyping, education, and low-to-medium volume products.',
  },
  {
    term: 'Synthesis vs Simulation',
    category: 'hardware',
    summary: 'Simulation: software model. Synthesis: compiling to actual hardware gates.',
    detail:
      'Verilog simulation (like what this app does) runs the hardware description as a software program. It is fast and great for verification but runs thousands of times slower than real hardware. Synthesis takes Verilog and produces a gate-level netlist that can be programmed into an FPGA or used to create an ASIC mask. Tools like Yosys, Vivado, and Quartus perform synthesis. This app is a simulator only – the generated Verilog would still need synthesis tools to run on real hardware.',
  },
  {
    term: 'Blocking vs Non-blocking Assignments',
    category: 'hardware',
    summary: '= is blocking (immediate). <= is non-blocking (scheduled for end of timestep).',
    detail:
      'In Verilog, `=` (blocking) executes immediately, in order, like C code. `<=` (non-blocking) schedules the assignment to happen at the end of the current simulation timestep. In always @(posedge clk) blocks, always use `<=` to avoid race conditions between flip-flops. Use `=` in combinational always blocks (always @(*)) for correct simulation. The app generates `<=` for all sequential assignments.',
  },
  {
    term: 'Setup and Hold Time',
    category: 'hardware',
    summary: 'Data must be stable before (setup) and after (hold) the clock edge.',
    detail:
      'A flip-flop requires the input data (D) to be stable for a minimum time before the clock edge (setup time) and after the clock edge (hold time). If these timing constraints are violated, the flip-flop may enter a metastable state. Timing analysis is performed during synthesis to ensure all paths meet these requirements. This app\'s simulation ignores propagation delays but real hardware must account for them.',
  },
  {
    term: 'Metastability',
    category: 'hardware',
    summary: 'When a flip-flop cannot resolve to 0 or 1 – a danger in cross-domain signals.',
    detail:
      'Metastability occurs when a flip-flop\'s setup or hold time is violated. The output hangs between 0 and 1 for an indeterminate time before resolving. This causes data corruption. The primary cause is crossing clock domains (sending a signal generated by clock A to a circuit using clock B). The solution is a synchronizer: two flip-flops in series that give the metastable signal time to resolve before it enters the rest of the logic.',
  },
  {
    term: 'Clock Domains',
    category: 'hardware',
    summary: 'Regions of logic driven by the same clock signal.',
    detail:
      'In complex hardware, different parts of the circuit may run at different clock frequencies. Each region is a "clock domain." Signals crossing between domains can cause metastability. Solutions include synchronizers, async FIFOs, and CDC (Clock Domain Crossing) analysis tools. This app uses a single clock domain for simplicity.',
  },
  {
    term: 'Memory-Mapped I/O',
    category: 'firmware',
    summary: 'Peripherals appear as memory addresses to the CPU.',
    detail:
      'In memory-mapped I/O (MMIO), peripheral registers are assigned specific addresses in the CPU\'s address space. A read or write to 0x4000_0000 is not RAM access – it goes to the peripheral\'s CONTROL register. The CPU\'s bus decoder routes the transaction to the correct peripheral based on the address. This is how every ARM Cortex-M, RISC-V, and x86 processor talks to peripherals. The address map is defined by the SoC vendor and documented in the reference manual.',
  },
  {
    term: 'Interrupts',
    category: 'firmware',
    summary: 'Hardware signals the CPU to pause and handle an event.',
    detail:
      'An interrupt (IRQ) is an electrical signal from hardware to the CPU\'s interrupt controller (e.g., NVIC on ARM Cortex-M). When asserted, the CPU finishes its current instruction, saves its state (registers) to the stack, and jumps to the interrupt handler (ISR). After the handler returns, the CPU restores state and resumes the main loop. Interrupt-driven I/O is far more efficient than polling for low-frequency events. Always clear the interrupt source at the end of the ISR.',
  },
  {
    term: 'DMA',
    category: 'firmware',
    summary: 'Direct Memory Access – hardware transfers data without CPU intervention.',
    detail:
      'A DMA controller can move data between peripherals and memory (or memory to memory) without the CPU executing each transfer. The CPU sets up the DMA descriptor (source, destination, count) and starts the transfer. The DMA raises an interrupt when done. DMA is essential for high-speed data transfers like audio, video, and high-baudrate serial. Without DMA, every byte would require CPU attention, burning most of the CPU\'s time on data movement.',
  },
  {
    term: 'Volatile Reads/Writes',
    category: 'firmware',
    summary: 'Tells the compiler not to cache MMIO register values.',
    detail:
      'The Rust compiler (and C/C++ compilers) optimize by caching variable values in CPU registers and eliminating "redundant" loads. For MMIO registers, this is wrong: the hardware can change STATUS between two reads, and the compiler must re-read from the address each time. `read_volatile` and `write_volatile` in Rust (and `volatile` in C) disable these optimizations for a specific access. Forgetting volatile is a common and dangerous firmware bug.',
  },
  {
    term: 'Rust Ownership for Driver Design',
    category: 'firmware',
    summary: 'Ownership prevents aliased mutable access to hardware registers.',
    detail:
      'In C firmware, it\'s easy to accidentally have two parts of code write to the same peripheral register concurrently, causing data corruption. Rust\'s ownership system makes this a compile-time error: only one part of code can hold a mutable reference to the driver struct at a time. The `&self` vs `&mut self` distinction enforces access rules. Combined with `unsafe` blocks that are clearly marked, Rust makes hardware driver bugs much more visible.',
  },
];
